# Executes quarantined tests in the outerloop
name: Outerloop Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  generate_tests_matrix:
    name: Generate test runsheet
    runs-on: windows-latest
    if: ${{ github.repository_owner == 'dotnet' }}
    outputs:
      runsheet: ${{ steps.generate_tests_matrix.outputs.runsheet }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # We need to build the whole solution, so that we can interrogate each test project
      # and find out whether it contains any quarantined tests.
      - name: Build the solution
        run: |
          ./build.cmd -restore -build -c Release -ci /p:CI=false /p:GeneratePackageOnBuild=false /p:InstallBrowsersForPlaywright=false

      - name: Generate test runsheet
        id: generate_tests_matrix
        run: |
          ./build.cmd -test /p:TestRunnerName=QuarantinedTestRunsheetBuilder /p:RunQuarantinedTests=true -c Release -ci /p:CI=false /p:Restore=false /p:Build=false /bl:./artifacts/log/Release/runsheet.binlog

      - name: Upload logs, and test results
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: logs-runsheet
          path: |
            ${{ github.workspace }}/artifacts/log/*/runsheet.binlog
            ${{ github.workspace }}/artifacts/log/*/TestLogs/**
            ${{ github.workspace }}/artifacts/tmp/*/combined_runsheet.json
          retention-days: 5

  run_tests:
    name: Test
    needs: generate_tests_matrix
    strategy:
      fail-fast: false
      matrix:
        tests: ${{ fromJson(needs.generate_tests_matrix.outputs.runsheet) }}

    runs-on: ${{ matrix.tests.os }} # Use the OS from the matrix
    if: ${{ github.repository_owner == 'dotnet' }}

    steps:
      - name: Trust HTTPS development certificate
        if: runner.os == 'Linux'
        run: dotnet dev-certs https --trust

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Verify Docker is running
        # nested docker containers not supported on windows
        if: runner.os == 'Linux'
        run: docker info

      - name: Install Azure Functions Core Tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test ${{ matrix.tests.label }}
        env:
          CI: false
        run: |
          ${{ matrix.tests.command }}

      - name: Upload logs, and test results
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ matrix.tests.project }}-${{ matrix.tests.os }}-logs
          path: |
            ${{ github.workspace }}/artifacts/log/*/TestLogs/**/*.log
            ${{ github.workspace }}/artifacts/TestResults/*/*.dmp
          # Longer retention time to allow scanning runs for quarantined test results
          retention-days: 30

      - name: Trx results
        if: always()
        id: upload-logs
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ matrix.tests.project }}-${{ matrix.tests.os }}-trx
          path: |
            ${{ github.workspace }}/artifacts/TestResults/*/*.trx
          # Longer retention time to allow scanning runs for quarantined test results
          retention-days: 30

  results:
    if: always()
    runs-on: ubuntu-latest
    name: Final Results
    needs: run_tests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # get all the test-job-result* artifacts into a single directory
      # note: download after the checkout, otherwise the checkout will clear the downloaded
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          pattern: '*-trx'
          path: ${{ github.workspace }}/artifacts/all-trx

      - name: Generate test results summary
        if: always()
        env:
          CI: false
        run: >
          ${{ github.workspace }}/dotnet.sh run --project ${{ github.workspace }}/tools/GenerateTestSummary/GenerateTestSummary.csproj -- ${{ github.workspace }}/artifacts/all-trx --combined
